import { defineUserConfig, defaultTheme } from 'vuepress';

export default defineUserConfig({
  base: '/',
  lang: 'zh-CN',
  title: 'Frontend Starter',
  description: '',
  theme: defaultTheme({
    notFound: ['404 Not Found'],
    contributors: false,
    navbar: [],
    sidebar: [
      {
        text: '基础 Basic',
        collapsible: true,
        children: [
          '/basic/HTTP & HTML.md',
          '/basic/CSS.md',
          '/basic/JavaScript.md',
          '/basic/jQuery.md',
          '/basic/Bootstrap.md',
          '/basic/Webpack.md',
          '/basic/微信小程序.md',
          '/basic/编程题.md',
          '/basic/其他.md',
          '/basic/综合.md',
        ],
      },
      {
        text: '进阶 Advanced',
        collapsible: true,
        children: [
          '/advanced/JS基础.md',
          '/advanced/HTML.md',
          '/advanced/CSS.md',
          '/advanced/浏览器.md',
          '/advanced/框架通识.md',
          '/advanced/Vue.md',
          '/advanced/React.md',
          '/advanced/性能.md',
          '/advanced/工程化.md',
          '/advanced/HTTP.md',
          '/advanced/设计模式.md',
        ],
      },
      {
        text: '精选 Selected',
        collapsible: true,
        children: [
          '/selected/HTML模块.md',
          '/selected/CSS模块.md',
          '/selected/JS模块.md',
          '/selected/ES6模块.md',
          '/selected/浏览器模块.md',
          '/selected/React模块.md',
          '/selected/Vue模块.md',
          '/selected/Node模块.md',
          '/selected/前端工程相关.md',
          '/selected/移动多端开发.md',
          '/selected/小程序模块.md',
          '/selected/前端安全模块.md',
          '/selected/性能优化相关.md',
          '/selected/HTTP模块.md',
          '/selected/常用设计模式.md',
          '/selected/框架通识.md',
          '/selected/排序算法.md',
          '/selected/计算机通识.md',
        ],
      },
      {
        text: '高频 Frequency',
        collapsible: true,
        children: ['/frequency/高频考点.md', '/frequency/性能优化.md'],
      },
      {
        text: '原理 Principle',
        collapsible: true,
        children: [
          '/principle/React.md',
          '/principle/Vue.md',
          '/principle/Webpack.md',
          '/principle/Node.md',
          '/principle/JavaScript.md',
          '/principle/综合.md',
        ],
      },
      {
        text: '实战 React',
        collapsible: true,
        children: [
          '/experience/react-reference/函数式组件-写前自问.md',
          '/experience/react-reference/性能优化-props.md',
          '/experience/react-reference/性能优化-state.md',
          '/experience/react-reference/性能优化-状态管理.md',
          '/experience/form-design/表单设计器概述.md',
          '/experience/form-design/表单设计器渲染.md',
        ],
      },
      { text: '实战 JS', collapsible: true, children: ['/basic/JS提升/事件循环.md'] },
      {
        text: '通用',
        collapsible: true,
        children: ['/experience/common-tips/markdown说明.md', '/experience/common-tips/异步优化.md'],
      },
    ],
  }),
});
